spring:
    application:
        name: payment-gateway-integration
    boot:
        admin:
            client:
                url: http://localhost:8084
                username: admin
                password: admin
                instance:
                    prefer-ip: true

    service:
        payment:
            #    payment: https://hub.hackload.kz/payment-provider/common
            url: https://hub.hackload.kz/event-provider/common
            merchant_id: mnp
            merchant_password: PLtqREQEVtt1g4#@FC@bxCe6H5
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
server:
    port: 8083